lib/index.d.ts
Sorry my bad, the original types will cause the type guard failed.
=> fix: types guard

src/_utils.ts
resolves https://github.com/nuxt/framework/issues/1559
resolves https://github.com/nuxt/framework/issues/1573
will also want to port to externality's identical util
=> fix: exclude windows drive letters from protocols

src/utils.ts, test/utils.test.mjs
https://github.com/nuxt/framework/pull/1648
=> feat: add `sanitizeURIComponent` and `sanitizeFilePath` helpers

README.md
The typescript definition for the second argument is :
```ts
interface ResolveOptions {
url?: string | URL | (string | URL)[];
extensions?: string[];
conditions?: string[];
}
```
Guessing this is a doc inconsistency as the code example uses `url`
=> docs: fix resolve url argument

src/_utils.ts, src/syntax.ts, src/utils.ts, test/utils.test.mjs
On windows current regexp from this url gets incorrect protocol:
```
file:///C:/path
```
- Incorrect: `file:///C`
- Correct: `file`
This PR fixes it making `{2,}` ungreedy, so it will end after the first `:`. (You can test it in https://regex101.com/)
Related: https://github.com/vitest-dev/vitest/issues/379
=> fix: get actual protocol for windows instead of protocol + drive

README.md
Reverts unjs/mlly#35
My bad, I just noticed jiti is locked to 0.2 of mlly, which `url` seem to be the least option
=> Revert "docs: update options for resolve"

src/analyze.ts, test/exports.test.ts
Add support for star exports with name
```js
export * as foo from 'file'
```
Previously, parsing result was:
```js
{
type: 'star',
specifier: undefined,
code: 'export * ',
start: 0,
end: 23
}
```
=> feat(findExports): support named star export

src/resolve.ts
This can cause `resolvePath` to fail because it tries (for example) `${id}/index`, where `index` may not be in the package.json `exports`.
=> fix: don't throw if module subpath not found

src/analyze.ts, test/exports.test.ts
The filtering introduced in #40 incidentally filtered out named exports like:
```js
[
{ type: 'named', names: ['foo', /* ... */] },
{ type: 'named', names: ['bar', /* ... */] },
]
```
to becomes
```js
[
{ type: 'named', names: ['bar', /* ... */] },
]
```
Due to both of the exports having undefined of the `name` property.
=> fix(findExports): filtering for named exports

src/analyze.ts, test/exports.test.ts
> fix `findExport` function:
> when handle a export code with trailing comma , EXPORT_NAMED_RE Regex with contain the last comma , which cause 
> genarage a blank name`(name='')` export
it seams easy to resolve this case by add filter `name!==''` to namedExport.names https://github.com/unjs/mlly/blob/b5d0a3fd832f4826ceac9f670ec1990172432b28/src/analyze.ts#L102
* A little confuse about Regex at present , will try to fix this by adjust the EXPORT_NAMED_RE syntax later
=> fix(findExports): export with trailing comma

src/analyze.ts, test/exports.test.ts
Adjust EXPORT_NAMED_RE regex not to match the `trailing comma & blank` in export name, so no need to filter !!name after split exports
=> fix(findExports): get exports with trailing comma

package.json, pnpm-lock.yaml, src/analyze.ts, test/exports.test.ts
This PR is designed to address this issue #34
example:
```ts
// export { foo } from 'foo1';
// exports default 'foo';
// export { useB, _useC as useC };
// export function useA () { return 'a' }
// export { default } from "./other"
// export async function foo () {}
// export { foo as default }
//export * from "./other"
//export * as foo from "./other"
/**
* export const a = 123
* export { foo } from 'foo1';
* exports default 'foo'
* export function useA () { return 'a' }
* export { useB, _useC as useC };
*export { default } from "./other"
*export async function foo () {}
* export { foo as default }
* export * from "./other"
export * as foo from "./other"
*/
export { bar } from 'foo2';
export { foobar } from 'foo2';
```
The expected length of matches should be "2", but instead we get …
=> feat(findExports): use acorn tokenizer to filter false positive exports

README.md, src/analyze.ts, test/exports.test.ts
Expose `fineExportNames` as a shortcut for `findExports` that only returns export names.
Add new `resolveModuleExportNames` that resolves and reads a module and lists it's available exports using static analayzes.
Note: I didn't include `resolveModuleExports` with additional loc data since seems not useful. But name uses `Names` suffix so we have space to introduce it later.
=> feat: `resolveModuleExportNames` and `findExportNames`

src/resolve.ts
We are sometimes wrongly detecting directories as files. This PR updates behaviour not to distinguish between them, but assume either might be true.
=> fix(resolve): always try to resolve url as dir too

src/analyze.ts, test/exports.test.ts
=> feat(findExports): support typescript enum exports

src/analyze.ts, test/exports.test.ts
close https://github.com/nuxt/framework/issues/7658
=> fix(findExports): correctly dedup named exports

src/analyze.ts, test/exports.test.ts, test/imports.test.ts
Fix the issue https://github.com/unjs/unbuild/issues/136 are use unbuild stub mode, when entry file content `export type XXX`
=> fix: ignore `type` imports and exports

src/analyze.ts, src/utils.ts, test/exports.test.ts
close https://github.com/antfu/unplugin-auto-import/issues/307
=> feat(findExports): support for exports destructuring

src/utils.ts, test/utils.test.ts
When you compose your Vue component like:
```html
<script setup lang="ts" generic="T extends any, O extends any">
// ...
</script>
```
its id will be served as `Foo.vue?vue&type=script&setup=true&generic=T%20extends%20any%2C%20O%20extends%20T%3CZ%7Ca%3E&lang`
in which `sanitizeURIComponent` is not able to sanitize `%20` making it writes to filename. In that sense, breaking the production build of Nuxt as the browser will interop the URL as a space (404).
& further discussion: #138
=> fix(sanitizeURIComponent): sanitize url escaping

.gitignore, src/resolve.ts, test/exports.test.ts, test/fixture/package/exports.mjs, test/fixture/package/node_modules/react-router-dom/package.json, test/fixture/package/node_modules/react-router-dom/server.js, test/fixture/package/node_modules/react-router-dom/server.mjs, test/fixture/package/package.json
This prevents `resolve` and functions relying on it (like `resolveModuleExportNames`) from crashing with
```
Error: ENOTDIR: not a directory, open '/___/mlly/test/fixture/package/exports.mjs/package.json'
```
This happens when trying to resolve the exports of `react-router-dom/server`. I've added a fixture that is a stripped down version of `react-router-dom@6.4.3`.
You can see the error when running the test without the fix.
=> fix(resolve): stop searching when module is resolved

README.md
In the code snippet the wrong function was imported. Now the correct function is getting imported.
=> doc: correct import name

src/analyze.ts, test/imports.test.ts
https://github.com/nuxt/nuxt/issues/20736
=> fix(findStaticImports): allow accents in import names

src/_utils.ts, src/resolve.ts
`resolvePath` return type is being lost when `resolvePathSync` is passed to `pcall` (Promise\<any\> instead of Promise\<string\>).
`resolve` has the same issue but its return type was being cast from Promise\<any\> to Promise\<string\> via the function signature. instead of casting any I updated `pcall`'s types to reflect what is happening which fixes `resolvePath` types to Promise\<string\>
=> fix: fix `resolvePath` return type

src/_utils.ts, src/analyze.ts, src/utils.ts, test/imports.test.ts
=> feat: `findTypeImports` for finding type imports 

src/syntax.ts, test/fixture/imports/js-cjs/index.js, test/fixture/imports/mixed/index.js, test/fixture/imports/mixed/package.json, test/syntax.test.ts
Resolves #186
We check for valid ESM modules to either use `.mjs` entries or `type: "module"` (this could later be improved to double check syntax on ESM too)
But when detecting valid CJS entries, we have to make sure there is no mixed syntax before validating module.
=> fix(isValidNodeImport): detect invalid cjs modules

src/analyze.ts, test/exports.test.ts
fix https://github.com/nuxt/nuxt/issues/22969
=> fix(findExports): support generator

src/syntax.ts, test/syntax.test.ts
resolve #195 
hi :wave: this PR fix the syntax detection by removing comments before testing the code string.
There's another solution, much safer but not the best perfomance wise. It's to use an AST combined with magic-string
=> fix: strip comment for syntax detection

src/syntax.ts, test/syntax.test.ts
Complementary to #196 to avoid regressions
Striping comments with regex is tricky. (see #56, #155 and added test in this PR -- thanks @danielroe for idea in https://github.com/unjs/mlly/pull/155#discussion_r1121596789!)
This PR makes stripping comments for syntax detection utils so users can opt-in.
In the future (maybe major versions) we might migrate to a native parser.
=> feat: make `stripComments` optional for syntax detection

src/_utils.ts, src/analyze.ts, test/imports.test.ts
fix  #153 
fix https://github.com/antfu/unplugin-auto-import/issues/332
=> fix(analyze): ignore conmments for imports detection

src/analyze.ts, test/exports.test.ts
Hi!
I am using `unplugin-auto-import` which rely on `unimport` which using this package `findExports` method. And found an edge case when it extract `export default`. The `unplugin-auto-import` can prevent using filename except when we use `export default`. In that case it will always looking for the file name and use it, but for example I use named default export like this:
`exampleStore.ts`:
```ts
const useExampleStore = defineStore({});
export default useExampleStore;
```
In the current version the `findExports` method it will always return the filename (exampleStore). In my case I want to get the name from the default (useExampleStore).
For this 
- I update the `ESMExport` interface with a new `namedDefault` in type.
- I create a new regex for named default export and also update the …
=> feat(findExports): extract name of default exports

src/analyze.ts, test/exports.test.ts
Issue: #226
Add optional field *declarationType* in `ESMExport`. If export type is `declaration`, this field should be a string value like `interface` `type` `enum` `const` or `function`.
This approach can solve the issue of not being able to distinguish what specific type 'declaration' is.
Issue: #226 
Unimport issue: [#318](https://github.com/unjs/unimport/issues/318)
Unimport pull request: [fix re-export ts enum type](https://github.com/unjs/unimport/pull/325)
=> feat: add declaration type in ESMExport

src/analyze.ts, test/imports.test.ts
-
Hey @pi0,
the last release is causing problems for imports formatted by prettier, where the comma is added at the end, like
```ts
import {
something,
somethingElse,
} from "package"
```
that causes errors in unimport:
This PR fixes that and adds a test to make sure we're covering that case. Cheers!
=> fix(parseStaticImport): omit empty import names

src/syntax.ts
https://github.com/huang-julien/nitro-applicationinsights/issues/58
https://github.com/unjs/nitro/issues/2308
hi :wave: this PR adds  a `stripCommentsFromCode` option for `isValidNodeImport`. 
I think the `stripComments` option from `detectSyntax` was made to avoid breaking anything in the ecosystem.
The issue lies in the non-legacy externals plugin in nitro which tries to inline `applicationinsights` import when it shouldn't due to applicationinsights having cjs syntax and esm syntax within its comments.
The goal of the PR is to open another PR in nitro to add a `stripCommentsFromCode` option for the `external` rollup plugin.
=> feat(isValidNodeImport): support `stripComments` option

src/cjs.ts
N/A
While crafting https://github.com/antfu/unconfig/pull/27, I stumbled upon the implementation of `interopDefault`. Upon closer examination, I found out that the implementation could be simplified and redundant code could be merged.
All tests passed on my machine locally.
=> refactor(interopDefault): simplify implementation

src/analyze.ts, src/cjs.ts, src/eval.ts, src/resolve.ts, src/syntax.ts, src/utils.ts
Added JSDocs to exported functions
> Any feedback is welcomed! 🙌
=> docs: added jsdocs to exported functions and types

src/analyze.ts, test/exports.test.ts
N/A
- [ x] 🐞 Bug fix (a non-breaking change that fixes an issue)
I find `findExports` got the wrong result from export inline object or array, such as: 
`export const foo = [ bar, baz, fgg ];`
or 
`export const foo = { bar, baz, fgg };`
It returns `[ "foo", "baz",  "fgg" ]`
but it should be only `[ "foo" ]`
I haven't checked other functions like `findTypeExports` `findTypeExports`
I have added some new tests and all tests passed on my machine locally.
=> fix(findExports): find declaration export with inline object or array

src/cjs.ts, test/interop.test.ts
Fixes regressions from https://github.com/unjs/jiti/issues/238
With https://github.com/unjs/mlly/commit/14eb72d0f571e06dcd127c0d5fec7b4fa49609f9, we no longer assign props to default export if it is a function that breaks many mixed cases.
**Note:** With new opt-in `preferNamespace` flag, we don't mix them anymore and return namespace as-is still.
=> fix(interopDefault): assign props to default function export

pnpm-lock.yaml, src/resolve.ts, test/resolve.test.ts
Should fix DEP0166 (DeprecationWarning: Use of deprecated double slash resolving...) as mentioned in 
- nuxt/icon#140
- unjs/nitro#2523
- etc.
Will not fix DEP0155 (DeprecationWarning: Use of deprecated trailing slash pattern mapping "./" in the "exports" field...).
=> fix(resolver): avoid double slashes when joining id with `/index`

src/analyze.ts, test/exports.test.ts
previously we required a space `export {` but commonly minifiers omit it: `export{`
=> fix(findExportNames): do not require space before named exports

src/analyze.ts, test/exports.test.ts
For exported function declarations (`export function(a, b, c)`), `findExports` includes the names of the function's parameter names as exported names.
The `EXPORT_DECAL_RE` regex that matches function declaration exports considers the parameters as 'extra names', but extra names only appear on variable declaration exports (const, let, var).
A simple check is added to prevent `findExports` to look for extra names matched by the regex on function declartion exports.
=> fix(findExports): exclude parameter names from function declaration export names
